### ISSUE TITLE
Connect the API through RabbitMQ and MinIO

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/k8-go-api#12]
Use the [comm package](https://github.com/k8-proxy/k8-go-comm/tree/develop) to provide a real response instead of the dummy one, basically the API would need to communicate with the rest of the API setup through RabbitMQ and MinIO.

An example of a code which is using the same library is this code:
https://github.com/k8-proxy/icap-service-1/tree/develop

An updated diagram is here:
<img width="795" alt="Screen Shot 2021-02-23 at 17 01 28" src="https://user-images.githubusercontent.com/5932628/109424089-e1a61c00-79ea-11eb-9c5c-0a68338685c1.png">

**Comment by mahnouman** [comment]
Hello @ibrahimk9000 and @mohitsengarr  ,,,,,, @azopat and @pranaysahith can support you with devop / Kubernetes setup when needed.

**Comment by GINAGC** [comment]
A new task will be created for this.
